export const UPDATE_SEARCH_FIELD = 'UPDATE_SEARCH_FIELD';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const UPDATE_RELEASE_YEAR = 'UPDATE_RELEASE_YEAR';
export const UPDATE_RATING = 'UPDATE_RATING';
export const UPDATE_SORT = 'UPDATE_SORT';
export const SET_SEARCH_IS_LOADING = 'SET_SEARCH_IS_LOADING';
export const SET_TOTAL_ROW_COUNT = 'SET_TOTAL_ROW_COUNT';
export const HAS_PENDING_CHANGES = 'HAS_PENDING_CHANGES';
