export const UPDATE_SEARCH_FIELD = 'UPDATE_SEARCH_FIELD';
export const CHANGE_PAGE = 'CHANGE_PAGE';
export const UPDATE_RELEASE_YEAR = 'UPDATE_RELEASE_YEAR';
export const UPDATE_RATING = 'UPDATE_RATING';
export const UPDATE_SORT = 'UPDATE_SORT';
